### ISSUE TITLE
ArrayOutOfBoundsException après avoir cliqué sur deux localisations

### ISSUE THREAD

**Issue by ISSOtm** [PramaInitiative/Phoebe#9]
J'ai cliqué sur deux localisations l'une à la suite de l'autre, et Phoebe a complètement freeze.
Comme j'étais dans Eclipse, voilà l'erreur complète :

> `Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
>   at java.util.Vector.get(Unknown Source)
>   at com.prama.phoebe.PhoebeWindow.setPathList(PhoebeWindow.java:280)
>   at com.prama.phoebe.PhoebeWindow.drawWindow(PhoebeWindow.java:198)
>   at com.prama.phoebe.PhoebeWindow$1.actionPerformed(PhoebeWindow.java:51)
>   at javax.swing.JComboBox.fireActionEvent(Unknown Source)
>   at javax.swing.JComboBox.setSelectedItem(Unknown Source)
>   at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
>   at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(Unknown Source)
>   at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
>   at java.awt.Component.processMouseEvent(Unknown Source)
>   at javax.swing.JComponent.processMouseEvent(Unknown Source)
>   at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(Unknown Source)
>   at java.awt.Component.processEvent(Unknown Source)
>   at java.awt.Container.processEvent(Unknown Source)
>   at java.awt.Component.dispatchEventImpl(Unknown Source)
>   at java.awt.Container.dispatchEventImpl(Unknown Source)
>   at java.awt.Component.dispatchEvent(Unknown Source)
>   at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
>   at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
>   at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
>   at java.awt.Container.dispatchEventImpl(Unknown Source)
>   at java.awt.Window.dispatchEventImpl(Unknown Source)
>   at java.awt.Component.dispatchEvent(Unknown Source)
>   at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
>   at java.awt.EventQueue.access$400(Unknown Source)
>   at java.awt.EventQueue$3.run(Unknown Source)
>   at java.awt.EventQueue$3.run(Unknown Source)
>   at java.security.AccessController.doPrivileged(Native Method)
>   at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
>   at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
>   at java.awt.EventQueue$4.run(Unknown Source)
>   at java.awt.EventQueue$4.run(Unknown Source)
>   at java.security.AccessController.doPrivileged(Native Method)
>   at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
>   at java.awt.EventQueue.dispatchEvent(Unknown Source)
>   at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
>   at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
>   at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
>   at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
>   at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
>   at java.awt.EventDispatchThread.run(Unknown Source)`

Je présuppose que l'erreur vient de `com.prama.phoebe.PhoebeWindow.setPathList(PhoebeWindow.java:280)`.

Ankeraout, c'est toi qui connais ton script. Je vais jeter un oeil quand même.

**Comment by ISSOtm** [comment]
Après test, voilà une update :
_Comportement normal_
1. Sélectionnez une map pour laquelle le logiciel ne trouve aucun chemin
2. Le logiciel continue de fonctionner

_Reproduire le bug_
1. Sélectionnez une map pour laquelle un chemin existe
2. Cochez la case "Mode détaillé"
3. Sélectionnez une map pour laquelle aucun chemin n'existe
4. Le logiciel crashe avec un "ArrayOutOfBoundsException"

Je tente un fix, on va voir.

**Comment by ISSOtm** [comment]
Ok, le bug venait bien de là où je pensais.
Fixé par le commit 32a049e414e6e4f7139583831ef5053f4dde6897, je ferme.
